// Code generated by protoc-gen-go. DO NOT EDIT.
// source: daemon.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	IsAdmin              bool     `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	IsBlocked            bool     `protobuf:"varint,5,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ViewedAt             int64    `protobuf:"varint,8,opt,name=viewed_at,json=viewedAt,proto3" json:"viewed_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *User) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *User) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *User) GetIsBlocked() bool {
	if m != nil {
		return m.IsBlocked
	}
	return false
}

func (m *User) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *User) GetViewedAt() int64 {
	if m != nil {
		return m.ViewedAt
	}
	return 0
}

type ListUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{1}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{2}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type CreateUserRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	IsAdmin              bool     `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{3}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *CreateUserRequest) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{4}
}
func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(dst, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type TouchUserRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchUserRequest) Reset()         { *m = TouchUserRequest{} }
func (m *TouchUserRequest) String() string { return proto.CompactTextString(m) }
func (*TouchUserRequest) ProtoMessage()    {}
func (*TouchUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{5}
}
func (m *TouchUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchUserRequest.Unmarshal(m, b)
}
func (m *TouchUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchUserRequest.Marshal(b, m, deterministic)
}
func (dst *TouchUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchUserRequest.Merge(dst, src)
}
func (m *TouchUserRequest) XXX_Size() int {
	return xxx_messageInfo_TouchUserRequest.Size(m)
}
func (m *TouchUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TouchUserRequest proto.InternalMessageInfo

func (m *TouchUserRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type TouchUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchUserResponse) Reset()         { *m = TouchUserResponse{} }
func (m *TouchUserResponse) String() string { return proto.CompactTextString(m) }
func (*TouchUserResponse) ProtoMessage()    {}
func (*TouchUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{6}
}
func (m *TouchUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchUserResponse.Unmarshal(m, b)
}
func (m *TouchUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchUserResponse.Marshal(b, m, deterministic)
}
func (dst *TouchUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchUserResponse.Merge(dst, src)
}
func (m *TouchUserResponse) XXX_Size() int {
	return xxx_messageInfo_TouchUserResponse.Size(m)
}
func (m *TouchUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TouchUserResponse proto.InternalMessageInfo

func (m *TouchUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	UpdateNickname       bool     `protobuf:"varint,2,opt,name=update_nickname,json=updateNickname,proto3" json:"update_nickname,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	UpdatePassword       bool     `protobuf:"varint,4,opt,name=update_password,json=updatePassword,proto3" json:"update_password,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	UpdateIsAdmin        bool     `protobuf:"varint,6,opt,name=update_is_admin,json=updateIsAdmin,proto3" json:"update_is_admin,omitempty"`
	IsAdmin              bool     `protobuf:"varint,7,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	UpdateIsBlocked      bool     `protobuf:"varint,8,opt,name=update_is_blocked,json=updateIsBlocked,proto3" json:"update_is_blocked,omitempty"`
	IsBlocked            bool     `protobuf:"varint,9,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{7}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *UpdateUserRequest) GetUpdateNickname() bool {
	if m != nil {
		return m.UpdateNickname
	}
	return false
}

func (m *UpdateUserRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UpdateUserRequest) GetUpdatePassword() bool {
	if m != nil {
		return m.UpdatePassword
	}
	return false
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateUserRequest) GetUpdateIsAdmin() bool {
	if m != nil {
		return m.UpdateIsAdmin
	}
	return false
}

func (m *UpdateUserRequest) GetIsAdmin() bool {
	if m != nil {
		return m.IsAdmin
	}
	return false
}

func (m *UpdateUserRequest) GetUpdateIsBlocked() bool {
	if m != nil {
		return m.UpdateIsBlocked
	}
	return false
}

func (m *UpdateUserRequest) GetIsBlocked() bool {
	if m != nil {
		return m.IsBlocked
	}
	return false
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{8}
}
func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(dst, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type AuthenticateUserRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserRequest) Reset()         { *m = AuthenticateUserRequest{} }
func (m *AuthenticateUserRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserRequest) ProtoMessage()    {}
func (*AuthenticateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{9}
}
func (m *AuthenticateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserRequest.Unmarshal(m, b)
}
func (m *AuthenticateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserRequest.Merge(dst, src)
}
func (m *AuthenticateUserRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserRequest.Size(m)
}
func (m *AuthenticateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserRequest proto.InternalMessageInfo

func (m *AuthenticateUserRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *AuthenticateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateUserResponse) Reset()         { *m = AuthenticateUserResponse{} }
func (m *AuthenticateUserResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateUserResponse) ProtoMessage()    {}
func (*AuthenticateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_daemon_fc8603b273fd7e35, []int{10}
}
func (m *AuthenticateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateUserResponse.Unmarshal(m, b)
}
func (m *AuthenticateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateUserResponse.Marshal(b, m, deterministic)
}
func (dst *AuthenticateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateUserResponse.Merge(dst, src)
}
func (m *AuthenticateUserResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateUserResponse.Size(m)
}
func (m *AuthenticateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateUserResponse proto.InternalMessageInfo

func (m *AuthenticateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "types.User")
	proto.RegisterType((*ListUsersRequest)(nil), "types.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "types.ListUsersResponse")
	proto.RegisterType((*CreateUserRequest)(nil), "types.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "types.CreateUserResponse")
	proto.RegisterType((*TouchUserRequest)(nil), "types.TouchUserRequest")
	proto.RegisterType((*TouchUserResponse)(nil), "types.TouchUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "types.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "types.UpdateUserResponse")
	proto.RegisterType((*AuthenticateUserRequest)(nil), "types.AuthenticateUserRequest")
	proto.RegisterType((*AuthenticateUserResponse)(nil), "types.AuthenticateUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	TouchUser(ctx context.Context, in *TouchUserRequest, opts ...grpc.CallOption) (*TouchUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/types.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/types.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) TouchUser(ctx context.Context, in *TouchUserRequest, opts ...grpc.CallOption) (*TouchUserResponse, error) {
	out := new(TouchUserResponse)
	err := c.cc.Invoke(ctx, "/types.UserService/TouchUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/types.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AuthenticateUser(ctx context.Context, in *AuthenticateUserRequest, opts ...grpc.CallOption) (*AuthenticateUserResponse, error) {
	out := new(AuthenticateUserResponse)
	err := c.cc.Invoke(ctx, "/types.UserService/AuthenticateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	TouchUser(context.Context, *TouchUserRequest) (*TouchUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	AuthenticateUser(context.Context, *AuthenticateUserRequest) (*AuthenticateUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_TouchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).TouchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.UserService/TouchUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).TouchUser(ctx, req.(*TouchUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AuthenticateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AuthenticateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.UserService/AuthenticateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AuthenticateUser(ctx, req.(*AuthenticateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "TouchUser",
			Handler:    _UserService_TouchUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "AuthenticateUser",
			Handler:    _UserService_AuthenticateUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daemon.proto",
}

func init() { proto.RegisterFile("daemon.proto", fileDescriptor_daemon_fc8603b273fd7e35) }

var fileDescriptor_daemon_fc8603b273fd7e35 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xf3, 0x69, 0x4f, 0x80, 0xc6, 0x7b, 0xe9, 0x36, 0x08, 0x1a, 0xf6, 0x00, 0x11, 0x42,
	0x39, 0x94, 0x8f, 0x0b, 0x97, 0x9a, 0x9e, 0x90, 0x10, 0x20, 0x43, 0xce, 0x91, 0x6b, 0xaf, 0xd4,
	0x55, 0x89, 0x6d, 0xbc, 0xeb, 0x56, 0xdc, 0xf8, 0x73, 0xfc, 0x00, 0xfe, 0x0a, 0xbf, 0x00, 0xed,
	0xae, 0xbd, 0x5e, 0x6c, 0x82, 0x2c, 0xd4, 0xe3, 0xbc, 0x37, 0x79, 0xfb, 0xfc, 0x66, 0x26, 0x70,
	0x27, 0x89, 0xe8, 0x2e, 0x4b, 0xd7, 0x79, 0x91, 0x89, 0x0c, 0x8d, 0xc5, 0xb7, 0x9c, 0x72, 0xf2,
	0xd3, 0x81, 0xd1, 0x86, 0xd3, 0x02, 0x61, 0x98, 0x46, 0x71, 0x9c, 0x95, 0xa9, 0xc0, 0x83, 0xa5,
	0xb3, 0xf2, 0xc2, 0xba, 0x44, 0x0b, 0x70, 0x53, 0x16, 0x5f, 0xa5, 0xd1, 0x8e, 0xe2, 0xa1, 0xa2,
	0x4c, 0x8d, 0x8e, 0xc1, 0x65, 0x7c, 0x1b, 0x25, 0x3b, 0x96, 0xe2, 0xd1, 0xd2, 0x59, 0xb9, 0xe1,
	0x94, 0xf1, 0x40, 0x96, 0xe8, 0x01, 0x00, 0xe3, 0xdb, 0x8b, 0x2f, 0x59, 0x7c, 0x45, 0x13, 0x3c,
	0x56, 0xa4, 0xc7, 0xf8, 0x1b, 0x0d, 0x48, 0x3a, 0x2e, 0x68, 0x24, 0x68, 0xb2, 0x8d, 0x04, 0x9e,
	0x2c, 0x9d, 0xd5, 0x30, 0xf4, 0x2a, 0x24, 0x10, 0x92, 0x2e, 0xf3, 0xa4, 0xa6, 0xa7, 0x9a, 0xae,
	0x90, 0x40, 0xa0, 0xfb, 0xe0, 0x5d, 0x33, 0x7a, 0xa3, 0x59, 0x57, 0xb1, 0xae, 0x06, 0x02, 0x41,
	0x10, 0xcc, 0xdf, 0x31, 0x2e, 0xe4, 0x67, 0xf1, 0x90, 0x7e, 0x2d, 0x29, 0x17, 0xe4, 0x15, 0xf8,
	0x16, 0xc6, 0xf3, 0x2c, 0xe5, 0x14, 0x3d, 0x82, 0x71, 0x29, 0x01, 0xec, 0x2c, 0x87, 0xab, 0xd9,
	0xe9, 0x6c, 0xad, 0x32, 0x59, 0xcb, 0xa6, 0x50, 0x33, 0xe4, 0xbb, 0x03, 0xfe, 0xb9, 0x72, 0xa5,
	0x50, 0xad, 0x66, 0x87, 0xe5, 0x74, 0xc2, 0xca, 0x23, 0xce, 0x6f, 0xb2, 0x22, 0xa9, 0x72, 0x34,
	0xf5, 0x7f, 0x06, 0x49, 0x5e, 0x02, 0xb2, 0x1d, 0x54, 0xde, 0x4f, 0x60, 0x24, 0x1d, 0xaa, 0xf7,
	0x5b, 0xd6, 0x15, 0x41, 0x9e, 0xc1, 0xfc, 0x73, 0x56, 0xc6, 0x97, 0xbd, 0x7c, 0x93, 0x17, 0xe0,
	0x5b, 0xdd, 0x7d, 0xdf, 0xf8, 0x31, 0x00, 0x7f, 0xa3, 0x86, 0xd2, 0x2f, 0x9d, 0x27, 0x70, 0xa8,
	0x67, 0xb8, 0x35, 0x41, 0x0c, 0xd4, 0xc7, 0xde, 0xd3, 0xf0, 0xfb, 0x3a, 0x8e, 0x7f, 0x45, 0xd5,
	0x88, 0x98, 0xa4, 0x47, 0xb6, 0xc8, 0x47, 0x2b, 0x6f, 0xd3, 0x31, 0x6e, 0xcd, 0xe2, 0xb1, 0x11,
	0x31, 0xb1, 0x4f, 0x94, 0xc8, 0x5d, 0x0d, 0xbf, 0xad, 0xb6, 0xd8, 0x9e, 0xcb, 0xf4, 0xcf, 0x05,
	0x7f, 0x0a, 0x7e, 0x23, 0x51, 0xef, 0xb9, 0xab, 0x7a, 0x0e, 0x6b, 0x11, 0x6b, 0xdb, 0xad, 0x26,
	0xaf, 0x75, 0x0c, 0x72, 0xc4, 0x76, 0x8c, 0x7d, 0xe3, 0xff, 0x00, 0x47, 0x41, 0x29, 0x2e, 0x69,
	0x2a, 0x58, 0x7c, 0x1b, 0x1b, 0x4a, 0x5e, 0x03, 0xee, 0x0a, 0xf6, 0x74, 0x73, 0xfa, 0x6b, 0x00,
	0x33, 0x59, 0x7e, 0xa2, 0xc5, 0x35, 0x8b, 0x29, 0x3a, 0x03, 0xcf, 0x9c, 0x1c, 0x3a, 0xaa, 0xfa,
	0xdb, 0x87, 0xb9, 0xc0, 0x5d, 0x42, 0x3f, 0x48, 0x0e, 0xd0, 0x39, 0x40, 0xb3, 0xf9, 0xa8, 0xee,
	0xec, 0x9c, 0xe3, 0xe2, 0xf8, 0x2f, 0x8c, 0x11, 0x39, 0x03, 0xcf, 0x6c, 0xb6, 0xb1, 0xd1, 0xbe,
	0x0c, 0x63, 0xa3, 0x73, 0x04, 0xda, 0x46, 0x33, 0x1d, 0x63, 0xa3, 0xb3, 0xf7, 0xc6, 0x46, 0x77,
	0x94, 0xe4, 0x00, 0x6d, 0x60, 0xde, 0x8e, 0x16, 0x3d, 0xac, 0x7e, 0xb0, 0x67, 0x88, 0x8b, 0x93,
	0xbd, 0x7c, 0x2d, 0x7b, 0x31, 0x51, 0xff, 0xe6, 0xcf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf7,
	0x07, 0x94, 0xa6, 0xdd, 0x05, 0x00, 0x00,
}
